### ISSUE TITLE
sTeX based HTML slides

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#10]
The idea here is to have a view where students can browse through slides like any either presentation. We already have slides in course notes. With this feature, we would like to "just have the slides" with the overlays intact (and working).  

Would like to have this before the next semester starts (Oct 20)

**Comment by kohlhase** [comment]
Actually not just have the students browse through the slides, but I would like to use the HTML slides to actually give the lectures. And eventually, I will want some of the added-value services that HTML + sTeX affords us available to me as a lecturer.

**Comment by kohlhase** [comment]
One prerequisite for this is to get the overlays (partial revealment of slide material) from the sTeX to the HTML, @Jazzpirate will probably have to do some backend work for this.

**Comment by abchugh** [comment]
We have a slides view available for students now. Will open a separate issue when we focus on features for the lecturer.
