### ISSUE TITLE
a

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#101]
A content ERROR was logged by "a user" at the following url:

https://courses.voll-ki.fau.de/

## The issue as described by the user:
```
ad
```

## The text highlighted while reporting this issue:
```
and competencies
```

**Comment by kohlhase** [comment]
@abchugh where have the helpful URLs gone? here I have almost no chance to do something about the errors.

**Comment by abchugh** [comment]
This is me trying to debug the firefox hanging issue. Please ignore
