### ISSUE TITLE
Drill cards

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#11]
For all definitions, we should have a mode that allows students to drill on them. I.e. a mode where they are shown the terms (from \definiendum) in random order and can write or say the definitions (and self-grade themselves on them) and then the good ones are dropped from the pool (or their frequency is dropped) and the unknown ones are repeated (randomly). 

Would be helpful for students to quickly revise the material especially before oral exams

**Comment by kohlhase** [comment]
I would really like to see this feature soon (actually yesterday I should have seen this coming), the big AI exam is on Feb 13. 2023 (less than two months away) and this might be a "killer feature"  for the SSFC even in a very simple form. 

It should be relatively easy to derive that from the guided tours interface (probably with the help of @Jazzpirate or @jbetzendahl for the ): collect all the definitions (introduced) in the course, collect all the (primary) verbalizations of these, and put them into the drill list.  And then cycle through the drill list, showing the student the verbalization on a page that has * an "I know" button (also see https://gitos.rrze.fau.de/voll-ki/fau/system/SSFC/-/issues/38), 
* a "show-me" button that shows the definition (with its own "I know" button),  and 
* a "next" button that just goes to the next verbalization in the list. 

I am sure that this would already be very valuable to students, and a great christmas gift (I am aware that we will not be able to have it ready in time, but maybe a new-years surprise?). 

cc: @Jazzpirate @jbetzendahl

**Comment by kohlhase** [comment]
We have a first version of this, thanks.
