### ISSUE TITLE
User reported ERROR course/snip/getting-most.en.xhtml

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#115]
A content ERROR was logged by "Moritz Gorny" at the following url:

https://courses.voll-ki.fau.de/de/course-notes/ai-1?inDocPath=%7Eb04e99f9

## The issue as described by the user:
```
Überschrift fehlt?
```

## The text highlighted while reporting this issue:
```
I
    n this
subsec
```

### The selected text was in the following section hierarchy:

**_INNERMOST SECTION FIRST_**

1. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/course/snip/getting-most.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=course/snip/getting-most.en.xhtml&bindings=0_0_7yV

2. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/course/sec/getting-most.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=course/sec/getting-most.en.xhtml&bindings=0_0_1Te

3. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/course/sec/preliminaries.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=course/sec/preliminaries.en.xhtml&bindings=0_0_s

4. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/course/notes/notes1.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=course/notes/notes1.xhtml

**Comment by kohlhase** [comment]
Danke für die Fehlermeldung. Habe es behoben, erscheint beim nächsten Update.
