### ISSUE TITLE
Interface for auto-graded tests

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#12]
This feature will have multiple uses:
1. Help understand which student's weak spots (i.e. develop usermodel's for VoLL-KI).
2. Help students prepare for exams  (a generalization of #11)
3. Self-test for the M.Sc. in AI

**Comment by abchugh** [comment]
Questions for self-test are being prepared here:
https://gl.mathhub.info/problems/maai-test

**Comment by kohlhase** [comment]
This also has the SSFC issue https://gitos.rrze.fau.de/voll-ki/fau/SSFC/-/issues/28
