### ISSUE TITLE
User reported ERROR probabilistic-reasoning/snip/prob-intro.en.xhtml

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#146]
A content ERROR was logged by "a user" at the following url:

https://courses.voll-ki.fau.de/course-view/ai-2?slideNum=1&viewMode=SLIDE_MODE&audioOnly=false&sectionId=4d37f673

## The issue as described by the user:
```
Link missing
```

## The text highlighted while reporting this issue:
```
??
```

### The selected text was in the following section hierarchy:

1. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/probabilistic-reasoning/snip/prob-intro.en.tex<br/>FetchURL: https://stexmmt.mathhub.info/archive=MiKoMH/AI&filepath=probabilistic-reasoning/snip/prob-intro.en.xhtml

**Comment by Jazzpirate** [comment]
I would guess it's just a matter of building the files in order... possibly, just building the file again might fix it. I'll try

**Comment by Jazzpirate** [comment]
...indeed, it did: https://stexmmt.mathhub.info/:sTeX/fulldocument?archive=MiKoMH/AI&filepath=probabilistic-reasoning/snip/prob-intro.en.xhtml
