### ISSUE TITLE
Anzeige nicht lesbar

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#149]
A content ERROR was logged by "Moritz Paesler" at the following url:

https://courses.voll-ki.fau.de/de/course-notes/ai-1?inDocPath=uqur5k.6deehn.-sbnw8.8gfg3a%7Eddb42797

## The issue as described by the user:
```
Das Intervall / die Intervalle, die hier stehen, werden vom Browser übereinander geschrieben angezeigt und sind daher nicht lesbar.
```

## The text highlighted while reporting this issue:
```
2;[3,2]
```

### The selected text was in the following section hierarchy:

**_INNERMOST SECTION FIRST_**

1. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/game-play/slides/alphabeta-ex.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=game-play/slides/alphabeta-ex.en.xhtml&bindings=0_6_13kT990Rjia

2. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/game-play/sec/alphabeta.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=game-play/sec/alphabeta.en.xhtml&bindings=0_0_3AZ7xO

3. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/game-play/sec/game-play.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=game-play/sec/game-play.en.xhtml&bindings=0_0_d4U

4. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/course/sec/gps.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=course/sec/gps.en.xhtml&bindings=0_0_3a

5. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/course/notes/notes1.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=course/notes/notes1.xhtml

**Comment by Jazzpirate** [comment]
This is already broken in the sources, since the PDF looks the same

**Comment by kohlhase** [comment]
Actually, the problem here is that we do not have overlays in `beamerarticle.sty`. The source works fine with `beamer.cls`. 
We need a more principled way of handling this.

**Comment by kohlhase** [comment]
has been fixed with slideshow
