### ISSUE TITLE
Small competency indicator in the TOC

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX-React#152]
I like the new large yellow competency indicator bars in principle but I am wondering whether they get into the way with reading. 
I think that the following idea might be less invasive and give more overview: 

We add a little "competency indicator" that is square and line-height at the beginning of each TOC entry. It should just contain two bars of the "average remember" and "average understand" (and maybe the "average apply") on the concepts introduced in this section. Essentially just just the two bars you have in the yellow in very small. This would give students an on-the-glance overview how well they are doing on the course.  These indicators could have a hover that is essentially the yellow thing that is currently in the notes.

**Comment by abchugh** [comment]
There are 157 items on the ai-1 dashboard. Naively done, each of section/subsection will make request to lms for several uris every time notes are loaded.

We would also like to have these indicators updated along with manual user updates or when a user answers a question.

So, we want to think about performance, aggregated fetches and smart updates with this feature

**Comment by kohlhase** [comment]
I agree, I was worried about this as well. I am adding Jonas as the person who knows about the LMS

**Comment by lambdaTotoro** [comment]
We will probably need to keep a running list of these things that we need often and quickly and then the LMS just needs to cache them. Can you think of anything else, besides this concrete example? For me, only the dependency tree comes to mind.

**Comment by abchugh** [comment]
Most of the work is building a smart cache at the frontend. 

LMS can help by returning a list of URIs that were updated because of an event. This way we can update the cache with exactly what's needed.

**Comment by kohlhase** [comment]
I do not think that efficiency is the main problem here; It is completely acceptable if the competency indicators come in "when there is time". And it is also OK, if they update slowly.

**Comment by abchugh** [comment]
Yes, time efficiency/latency is not too important. We need to make sure that the frontend doesn't unnecessarily overload LMS server with too many requests.

**Comment by kohlhase** [comment]
this is done with the review at the end of the section
