### ISSUE TITLE
Unicode wird nicht angezeigt

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#155]
A content ERROR was logged by "a user" at the following url:

https://courses.voll-ki.fau.de/course-notes/iwgs-1?inDocPath=7y4z5l.80wq9k%7E47c70fe3

## The issue as described by the user:
```
Auf den Slides ist hier ein richtiges Zeichen, aberin Alea werden nur ??? angezeigt.
```

## The text highlighted while reporting this issue:
```
???
```

### The selected text was in the following section hierarchy:

**_INNERMOST SECTION FIRST_**

1. GitLab: https://gl.mathhub.info/MiKoMH/GenCS/-/blob/main/source/codes/slides/utfcodes.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/GenCS&filepath=codes/slides/utfcodes.en.xhtml&bindings=1_5_gN8RZW80NI6dYx4

2. GitLab: https://gl.mathhub.info/MiKoMH/IWGS/-/blob/main/source/progintro/sec/unicode.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/IWGS&filepath=progintro/sec/unicode.en.xhtml&bindings=1_1_cCnlFW

3. GitLab: https://gl.mathhub.info/MiKoMH/IWGS/-/blob/main/source/progintro/sec/datastructures.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/IWGS&filepath=progintro/sec/datastructures.en.xhtml&bindings=1_0_bti

4. GitLab: https://gl.mathhub.info/MiKoMH/IWGS/-/blob/main/source/course/notes/notes-part1.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/IWGS&filepath=course/notes/notes-part1.xhtml

**Comment by kohlhase** [comment]
Danke für die Nachricht, aber der Mechanismus wird in rusTeX gerade geändert, daher nicht mehr relevant.
