### ISSUE TITLE
User reported ERROR game-play/slides/mcts-illustration.en.xhtml

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#162]
A content ERROR was logged by "Philipp Hofmann" at the following url:

https://courses.voll-ki.fau.de/course-notes/ai-1?inDocPath=uqur5k.-9gxrd5.dwvm60%7Ec43f65ba

## The issue as described by the user:
```
display is off.
-> overlayed with graph

OS: WIN
Browser: Firefox Version 120.0
```

## The text highlighted while reporting this issue:
```
Expansions: 0, 0, 0avg. reward: 0, 0, 0 Expansions: 0, 1, 0avg. reward: 0, 10, 0 Expansions: 1, 1, 0avg. reward: 70, 10, 0 Expansions: 1, 1, 1avg. reward: 70, 10, 40 Expansions: 1, 1, 2avg. reward: 70, 10, 35 Expansions: 2, 1, 2avg. reward: 60, 10, 35 Expansions: 2, 2, 2avg. reward: 60, 55, 35 Expansions: 2, 2, 2avg. reward:
60, 55, 35
```

### The selected text was in the following section hierarchy:

**_INNERMOST SECTION FIRST_**

1. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/game-play/slides/mcts-illustration.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=game-play/slides/mcts-illustration.en.xhtml&bindings=0_2_fP4DvIDsm

2. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/game-play/sec/mcts.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=game-play/sec/mcts.en.xhtml&bindings=0_0_VxLWIY

3. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/game-play/sec/game-play.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=game-play/sec/game-play.en.xhtml&bindings=0_0_d4U

4. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/course/sec/gps.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=course/sec/gps.en.xhtml&bindings=0_0_3a

5. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/course/notes/notes1.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=course/notes/notes1.xhtml

**Comment by kohlhase** [comment]
this is a know issue, cannot change this at the moment. The PDF slides help.
