### ISSUE TITLE
Everything is overlapping

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#170]
A content ERROR was logged by "Jannik Lieb" at the following url:

https://courses.voll-ki.fau.de/de/course-view/ai-1?sectionId=c43f65ba&slideNum=5&viewMode=SLIDE_MODE&audioOnly=false

## The issue as described by the user:
```
The text of the graphic is overlapping, so i cannot really read the red text on the nodes
```

## The text highlighted while reporting this issue:
```
Max  
                                −∞;𝛼=−∞
```

### The selected text was in the following section hierarchy:

1. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/game-play/slides/alpha-pruning.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=game-play/slides/alpha-pruning.en.xhtml

**Comment by kohlhase** [comment]
this is a known issue, we are working on this.
