### ISSUE TITLE
Mysterious line containing single comma

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#180]
A content ERROR was logged by "Marcel Schütz" at the following url:

https://courses.voll-ki.fau.de/course-view/lbs?slideNum=7&viewMode=SLIDE_MODE&audioOnly=false&sectionId=af406199

## The issue as described by the user:
```
This line contains nothing but a single comma which I couldn't locate anywhere in the sources...
```

## The text highlighted while reporting this issue:
```
,
```

### The selected text was in the following section hierarchy:

1. GitLab: https://gl.mathhub.info/MiKoMH/LBS/-/blob/main/source/mmt/slides/situation.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/LBS&filepath=mmt/slides/situation.en.xhtml

**Comment by kohlhase** [comment]
found it and fixed it (hint it was a single quote).
