### ISSUE TITLE
Indicate what parts of lecture have been covered 

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#19]
With PDFs this done by the instructor using a  "recorded syllabus" slide (table in front) that is updated after each lecture to indicate which sections of the course have been covered so far.

@mkolhase's suggestion is to have this functionality in the notes/slides UIs by augmenting the TOC. Something like the following:

1. Give all the sections which are "done" a yellow background and have them collapsed by default. 

2. The subsections of the current lecture, i.e. the last one will be unfolded and be the default entry point to the notes/slides.

3. The instructor should have a simple interface to update which sections have been 'covered'.

**Comment by kohlhase** [comment]
this is done.
