### ISSUE TITLE
The condition is missing

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#194]
A content ERROR was logged by "Christopher Roßbach" at the following url:

https://courses.voll-ki.fau.de/course-notes/ai-1?inDocPath=uqur5k.-pwo4h7.rdv8ha%7E62676549

## The issue as described by the user:
```
The condition on the set is not shown in the notes view
```

## The text highlighted while reporting this issue:
```
minimizes
                  #({𝑒∊𝐷𝑢|
                                𝑢∉𝐷𝑣, 𝐶𝑢𝑣∊𝐶, and (𝑒,𝑑)∉𝐶𝑢𝑣
                              })
```

### The selected text was in the following section hierarchy:

**_INNERMOST SECTION FIRST_**

1. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/csp/slides/least-constraining-variable.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=csp/slides/least-constraining-variable.en.xhtml&bindings=0_7_4MJEKtIMuR6bgam

2. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/csp/sec/csp-search.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=csp/sec/csp-search.en.xhtml&bindings=0_0_eQIf0wY

3. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/csp/sec/csp.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=csp/sec/csp.en.xhtml&bindings=0_0_3ngw

4. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/course/sec/gps.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=course/sec/gps.en.xhtml&bindings=0_0_3a

5. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/course/notes/notes1.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=course/notes/notes1.xhtml

**Comment by kohlhase** [comment]
thanks for the notification, but cannot reproduce.
