### ISSUE TITLE
User reported SUGGESTION pl0/slides/truth-tables.en.xhtml

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#199]
A content SUGGESTION was logged by "Moritz Gorny" at the following url:

https://courses.voll-ki.fau.de/de/course-notes/ai-1?inDocPath=2v696w.-qxa9pm.-z4t3oa%7Eeb0bdc5a

## The issue as described by the user:
```
Table is too dense
```

## The text highlighted while reporting this issue:
```
¬⊤𝖥⊥𝖳
                        
                          ∧⊤⊥⊤𝖳𝖥⊥𝖥𝖥
                        
                          ∨⊤⊥⊤𝖳𝖳⊥𝖳𝖥
```

### The selected text was in the following section hierarchy:

**_INNERMOST SECTION FIRST_**

1. GitLab: https://gl.mathhub.info/MiKoMH/GenCS/-/blob/main/source/pl0/slides/truth-tables.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/GenCS&filepath=pl0/slides/truth-tables.en.xhtml&bindings=0_8_gQLNyDmZX0C

2. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/logic/sec/proplog-formal.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=logic/sec/proplog-formal.en.xhtml&bindings=0_0_RYhK

3. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/logic/sec/proplog.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=logic/sec/proplog.en.xhtml&bindings=0_0_QhI

4. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/course/sec/krinf.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=course/sec/krinf.en.xhtml&bindings=0_0_OE

5. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/course/notes/notes1.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=course/notes/notes1.xhtml

**Comment by kohlhase** [comment]
works for me.
