### ISSUE TITLE
Improving expansion strategy of \inputref 

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#2]
Currently \inputref turn into expandable sections which are collapsed by default. We need their folding/unfloding strategy to be more customizable. Some interesting cases are mentioned here:

1.  Certain sections (especially when they are without a title) should be expanded by default. Example:
<img width="642" alt="Screenshot 2022-07-11 at 08 09 29" src="https://user-images.githubusercontent.com/5623836/178232053-bf43be76-a996-4b4c-aa96-a43f3340d34e.png">
 
2. Not all sections without a title should be auto=expanded.  For example, we should not auto-expand such sections in the top-level course notes document. Example:
![Screenshot 2022-07-11 145213](https://user-images.githubusercontent.com/5623836/178232491-f361a773-824c-40e7-962a-e98142dacbb1.png)

3. Sections inside slides should always be expanded. It should be perceived by readers as one continuous text.
<img width="671" alt="Screenshot 2022-07-11 at 08 43 07" src="https://user-images.githubusercontent.com/5623836/178233827-bce58a72-8cd9-4ad0-af51-e36a7bb6f881.png">

**Comment by abchugh** [comment]
One suggested solution:
The sTeX document should be able to specify inputref's expansion behavior. By default, the section is collapsed unless it is title-free. inputref can also indicate if the section needs to be auto-expanded or always-expanded (`case 3` above).

This means that the title-less section in `case 2` above should be given a title or inserted at the end of the section preceding it (`"Introduction"`) or at the begging of the section following it (`"Enough philosophy..."`) .

**Comment by Jazzpirate** [comment]
> The sTeX document should be able to specify inputref's expansion behavior

I agree, that smells like backend-functionality to me.

>By default, the section is collapsed unless it is title-free.

that part should be relatively easy. The exceptions worry me a bit more - I'll need to experiment a bit, but we can already agree on some kind of attribute-scheme for the intended behaviour(s)

**Comment by abchugh** [comment]
Sections whose titles are just URLs are auto expanded into place now (`case 1` and `case 2` above)

**Comment by abchugh** [comment]
for `case 3`. Detect is any parent of expandable node has CSS class `frame`. If it does, always auto-expand,

**Comment by abchugh** [comment]
Update: Auto-expanding mode limits the impact of this bug

**Comment by kohlhase** [comment]
I think this is probably (sufficiently) done?

**Comment by abchugh** [comment]
Yes, with the auto-expansion of inputref this is (mostly) a non-issue now.
