### ISSUE TITLE
User reported SUGGESTION logic/slides/sequent-calc-linearized.en.xhtml

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#201]
A content SUGGESTION was logged by "Moritz Gorny" at the following url:

https://courses.voll-ki.fau.de/de/course-notes/ai-1?inDocPath=2v696w.-qxa9pm.2q8kma%7E9b44417f

## The issue as described by the user:
```
Table isnt formatted nicely
```

## The text highlighted while reporting this issue:
```
#ℎ𝑦𝑝⊢𝑓𝑜𝑟𝑚𝑢𝑙𝑎𝑁𝐷𝑗𝑢𝑠𝑡1.1⊢𝐀∧𝐁
                                            Ax
                                          2.1⊢𝐁∧𝐸𝑟13.1⊢𝐀∧𝐸𝑙14.1⊢𝐁∧𝐀∧𝐼2,35.⊢𝐀∧𝐁⇒𝐁∧𝐀⇒𝐼4
```

### The selected text was in the following section hierarchy:

**_INNERMOST SECTION FIRST_**

1. GitLab: https://gl.mathhub.info/MiKoMH/GenCS/-/blob/main/source/logic/slides/sequent-calc-linearized.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/GenCS&filepath=logic/slides/sequent-calc-linearized.en.xhtml&bindings=0_6_1ewYDX7G5ZaJEBFo

2. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/logic/sec/proplog-nd.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=logic/sec/proplog-nd.en.xhtml&bindings=0_0_VvEMoA

3. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/logic/sec/proplog.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=logic/sec/proplog.en.xhtml&bindings=0_0_QhI

4. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/course/sec/krinf.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=course/sec/krinf.en.xhtml&bindings=0_0_OE

5. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/course/notes/notes1.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=course/notes/notes1.xhtml

**Comment by kohlhase** [comment]
good enough for me.
