### ISSUE TITLE
User reported ERROR csp/slides/min-conflicts-performance.en.xhtml

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#210]
A content ERROR was logged by "a user" at the following url:

https://courses.voll-ki.fau.de/course-view/ai-1?slideNum=3&viewMode=SLIDE_MODE&audioOnly=false&sectionId=18a48ff2

## The issue as described by the user:
```
formula is not shown. checked on chrome on ipad and mac. not sure about windows
```

## The text highlighted while reporting this issue:
```
=
```

### The selected text was in the following section hierarchy:

1. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/csp/slides/min-conflicts-performance.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=csp/slides/min-conflicts-performance.en.xhtml

**Comment by kohlhase** [comment]
cannot reproduce.
