### ISSUE TITLE
overflow default maxwidth of 600px for different page layouts

### ISSUE THREAD

**Issue by ux51ekac** [slatex/sTeX-React#22]
different page layouts will overflow the default max width settings for the main view container.
slides for example or any other document that is landscape will look broken (scrollbar is there but `600px` are not enough to show the full doc, which has `636.879px` style property).

is there any awareness for the page layout?

![image](https://user-images.githubusercontent.com/74305777/196942004-36273d4f-9f1d-403c-8c29-28f3d19a01f6.png)

**Comment by abchugh** [comment]
I think this issue is now fixed. Feel free to reopen if you need more adjustments.
