### ISSUE TITLE
wrong hover

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX-React#23]
In https://courses.voll-ki.fau.de/browser/%3AsTeX%2Fdocument%3Farchive%3DMiKoMH%2FAI%26filepath%3Dcourse%2Fnotes%2Fnotes.xhtml?inDocPath=-to8f9d.i4m5qz.mnzbzh.-wgxq4l
I get the hover 
<img width="856" alt="Screenshot 2022-11-03 at 15 42 58" src="https://user-images.githubusercontent.com/4037538/199752621-9e6158f6-0b6c-4036-ac88-3a131649ea02.png">
Note that the arrow (comes from `\grule`) seems to point to somewhere (fragment1) in comsem, that has something to do with  grammars, but is not the definition. And at least the linter has the right URI for it. 
<img width="839" alt="Screenshot 2022-11-03 at 15 43 37" src="https://user-images.githubusercontent.com/4037538/199752965-0acf25e2-3c72-458b-a800-cc730894c506.png">

I have no idea what is going on, so assigning us three.

**Comment by Jazzpirate** [comment]
This is currently not really a bug -  this is the result of a \definame{grammar-rule} in the document the hover comes from (the one related to FragmentOne).

The \definame asserts that that definition (the one in FragmentOne) is a definition of the conecpt "grammar-rule", hence MMT is at least *allowed* to pick that to show whenever someone hovers over a reference to grammar-rule.

The first error is therefore in the content: I don't think the hover should be marked up as a definition *for the concept "grammar-rule"*.

The second problem is that MT should be smarter in picking which Definition is shown on hover, if multiple exist. Unfortunately, that requires taking the document context into account in non-trivial ways. I already have that on my radar for when I redesign the MMT-part of things, but I'm currently not entirely sure what a good *and sufficiently efficient* criterion for picking the right document fragment is...

**Comment by kohlhase** [comment]
I think we should talk about this functionality in detail, I had an issue about it somewhere. I think solving this generally is on the critical path towards good guided tours.

**Comment by kohlhase** [comment]
Yes, here it is: https://gitos.rrze.fau.de/voll-ki/fau/SSFC/-/issues/17, deferring to that and closing here.
