### ISSUE TITLE
Mangled appearance

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#235]
A content ERROR was logged by "a user" at the following url:

https://courses.voll-ki.fau.de/course-notes/ai-1?inDocPath=-dys2fb.52bndu.23031l%7Eb344f669

## The issue as described by the user:
```
Source or rustex bug
```

## The text highlighted while reporting this issue:
```
{𝑠
                                    
                                                    −
                                                  
                                                  
                                                                  −
                                                                
                                                →
                                  𝑎
                                  apply
                                (𝑠,𝑎)|
                                    pre
                                  𝑎⊆𝑠}.
```

### The selected text was in the following section hierarchy:

**_INNERMOST SECTION FIRST_**

1. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/planning/slides/strips-semantics.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=planning/slides/strips-semantics.en.xhtml&bindings=0_6_4dbflZcFmIi

2. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/planning/sec/strips.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=planning/sec/strips.en.xhtml&bindings=0_2_3Ps4Oxyk

3. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/planning/sec/framework.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=planning/sec/framework.en.xhtml&bindings=0_0_3n8i

4. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/course/sec/planact.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=course/sec/planact.en.xhtml&bindings=0_0_d4o

5. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/course/notes/notes1.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=course/notes/notes1.xhtml

**Comment by kohlhase** [comment]
a rustex bug.
