### ISSUE TITLE
Anzeige Software Grafik

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#237]
A content ERROR was logged by "Clara Steinfels" at the following url:

https://courses.voll-ki.fau.de/de/course-notes/iwgs-1?inDocPath=3s62g3.-4aalx3%7Ed45b1796

## The issue as described by the user:
```
Ich weiß nicht, ob der Fehler an meinem Gerät liegt, aber bei mir erscheinen  in der Grafik zur Visualisierung von "Software" die Drei Begriffe, die hier in den unterschiedlichen Feldern stehen sollten, alle übereinander in dem Feld links oben, während die anderen Felder leer bleiben. 
```

## The text highlighted while reporting this issue:
```
data  
                                                  
                                                  hardware
```

### The selected text was in the following section hierarchy:

**_INNERMOST SECTION FIRST_**

1. GitLab: https://gl.mathhub.info/MiKoMH/GenICT/-/blob/main/source/programming/slides/hardware-software-programming.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/GenICT&filepath=programming/slides/hardware-software-programming.en.xhtml&bindings=1_0_JTg

2. GitLab: https://gl.mathhub.info/MiKoMH/IWGS/-/blob/main/source/progintro/sec/intro.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/IWGS&filepath=progintro/sec/intro.en.xhtml&bindings=1_0_2RP

3. GitLab: https://gl.mathhub.info/MiKoMH/IWGS/-/blob/main/source/progintro/sec/progintro.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/IWGS&filepath=progintro/sec/progintro.en.xhtml&bindings=1_0_Is

4. GitLab: https://gl.mathhub.info/MiKoMH/IWGS/-/blob/main/source/course/notes/notes-part1.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/IWGS&filepath=course/notes/notes-part1.xhtml

**Comment by kohlhase** [comment]
Das ist schade, aber f"r mich nicht zu fixen: auf Firefox funktioniert's.
