### ISSUE TITLE
Formatting is off

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#244]
A content ERROR was logged by "Philipp Hofmann" at the following url:

https://courses.voll-ki.fau.de/course-notes/ai-1?inDocPath=-dys2fb.52bndu.-uq2bt0%7E9b6806d2

## The issue as described by the user:
```
Formatting is off.
WIN 10, Firefox latest version
```

## The text highlighted while reporting this issue:
```
𝑆𝑡𝑎𝑟𝑡
                                                                            𝑂𝑛(𝐶,𝐴)𝑂𝑛(𝐴,𝑇)𝐶𝑙(𝐵)𝑂𝑛(𝐵,𝑇)𝐶𝑙(𝐶)
                                                  
                                
                                                  𝐶𝑙(𝐵)𝐶𝑙(𝐶)
                                                                              𝑀𝑜𝑣𝑒(𝐵,𝐶)
                                                                            ¬𝐶𝑙(𝐶),𝑂𝑛(𝐵,𝐶)
                                                  
                                
                                                  𝐶𝑙(𝐴)𝐶𝑙(𝐴)𝐶𝑙(𝐵)
                                                                              𝑀𝑜𝑣𝑒(𝐴,𝐵)
                                                                            ¬𝐶𝑙(𝐵)𝑂𝑛(𝐴,𝐵)
                                                  
                                
                                                  𝐶𝑙(𝐶)
                                                                              𝑀𝑜𝑣𝑒(𝐶,𝑇)
                                                                            𝐶𝑙(𝐴)𝑂𝑛(𝐶,𝑇)
                                                  
                                
                                                  𝑂𝑛(𝐴,𝐵)𝑂𝑛(𝐴,𝐵)𝑂𝑛(𝐵,𝐶)𝑂𝑛(𝐵,𝐶)
                                                                              𝐹𝑖𝑛𝑖𝑠ℎ
```

### The selected text was in the following section hierarchy:

**_INNERMOST SECTION FIRST_**

1. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/planning/slides/poplan-blocks.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=planning/slides/poplan-blocks.en.xhtml&bindings=0_12_1jxP5WizoBqphK5KFI

2. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/planning/sec/pop.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=planning/sec/pop.en.xhtml&bindings=0_2_Zhff2ERe

3. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/planning/sec/framework.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=planning/sec/framework.en.xhtml&bindings=0_0_3n8i

4. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/course/sec/planact.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=course/sec/planact.en.xhtml&bindings=0_0_d4o

5. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/course/notes/notes1.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=course/notes/notes1.xhtml

**Comment by kohlhase** [comment]
thanks for the notification, I have fixed this in the sources.
