### ISSUE TITLE
Flash Card Stack leer beim lernen/wiederholen

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#258]
A content ERROR was logged by "Max Kiebist" at the following url:

https://courses.voll-ki.fau.de/de/flash-cards/ai-1

## The issue as described by the user:
```
Ich kann keine Karten zum Stack hinzufügen (die Buttons rechts sind auch ausgegraut) und beim klicken auf lernen oder wiederholen bei einzelnen Themen bekomme ich sofort die Anzeige die ich ausgewählt habe (0 erinnert etc.) 
```

## The text highlighted while reporting this issue:
```
Sie haben sich an 0 erinnert und 0 von 0 Konzepten verstanden.
```

**Comment by kohlhase** [comment]
Danke für die Nachricht, das ist jetzt gefixt.
