### ISSUE TITLE
better treatment for references

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX-React#26]
The references are at the end of each included file, which is particularly ugly, if a section, chapter or so ends: 
 
<img width="680" alt="Screenshot 2022-11-14 at 20 53 54" src="https://user-images.githubusercontent.com/4037538/201753206-ec5bc81e-13be-4e23-a78b-6ea6a2041f5a.png">

The references should be "shown inline", e.g. on hover over `[Koh08`, and not be shown in the sections. We might want to have a collected references part at the end of the overall document, but I am not sure that this would be helpful.

**Comment by kohlhase** [comment]
this seems done.

**Comment by abchugh** [comment]
yes, @Jazzpirate had fixed this by having the document fragment level encoded in the URL
