### ISSUE TITLE
\fntype does not produce correct parentheses

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#267]
A content ERROR was logged by "Fake User: pa68rase " at the following url:

https://stex-active-doc.kwarc.info/course-notes/lbs?inDocPath=-btwcv5.-q0gwrt.-81zljk%7Eab251808

## The issue as described by the user:
```
`\fntype{\fntype\typeind\typebool}\typebool` should be displayed as `(ι⟶prop)⟶prop`, but it is instead displayed as `ι⟶prop⟶prop`.
```

## The text highlighted while reporting this issue:
```
𝜄→prop→prop
```

### The selected text was in the following section hierarchy:

**_INNERMOST SECTION FIRST_**

1. GitLab: https://gl.mathhub.info/MiKoMH/ComSem/-/blob/main/source/nlfrags/slides/type-raising.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/ComSem&filepath=nlfrags/slides/type-raising.en.xhtml&bindings=0_0_3I5BGOB

2. GitLab: https://gl.mathhub.info/MiKoMH/ComSem/-/blob/main/source/nlfrags/sec/type-lifting.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/ComSem&filepath=nlfrags/sec/type-lifting.en.xhtml&bindings=0_0_VwoVcE

3. GitLab: https://gl.mathhub.info/MiKoMH/ComSem/-/blob/main/source/nlfrags/sec/quantifier-scope-ambiguity.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/ComSem&filepath=nlfrags/sec/quantifier-scope-ambiguity.en.xhtml&bindings=0_0_TIX1a

4. GitLab: https://gl.mathhub.info/MiKoMH/LBS/-/blob/main/source/course/sec/topics.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/LBS&filepath=course/sec/topics.en.xhtml&bindings=0_0_3a

5. GitLab: https://gl.mathhub.info/MiKoMH/LBS/-/blob/main/source/course/notes/notes.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/LBS&filepath=course/notes/notes.xhtml

**Comment by jfschaefer** [comment]
It's a presentation error, but on the stex side (more concretely, a problem with the notation).
Anyway, I actually managed to fix it: https://gl.mathhub.info/smglom/logic/-/commit/7920ee823368cc4feac3c18bcda6ca8c883e3899

**Comment by kohlhase** [comment]
Thanks a lot.
