### ISSUE TITLE
Remove titles in unfolded sections

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#3]
See the duplicate title ( `"Document as Digital Objects"`) here:

<img width="642" alt="Screenshot 2022-07-11 at 08 09 29" src="https://user-images.githubusercontent.com/5623836/178241126-2ea45e5e-0792-4b3b-9852-69142e0dbe08.png">

**Comment by abchugh** [comment]
Should probably get rid of it while creating the HTML from stex (or perhaps in the source sTeX?) or maybe even come up with a new design for managing titles.

**Comment by abchugh** [comment]
This is somewhat less concerning now with auto expanding notes. We now don't duplicate the titles by default. But when 'expandable' option is turned on, there is still duplication.

**Comment by kohlhase** [comment]
I think this is done; closing.

**Comment by kohlhase** [comment]
I do not either.
