### ISSUE TITLE
ERROR in csp/slides/fourqueens-ex.en.xhtml

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#33]
A content ERROR was logged by a user at the following url:

https://courses.voll-ki.fau.de/course-view/ai-1?deckId=MiKoMH%2FAI%7C%7Ccsp%2Fsec%2Fcsprop-localsearch.en.xhtml&slideNum=2&viewMode=COMBINED_MODE&audioOnly=false

## The issue as described by the user:
```
incomplete...
```

## The text highlighted while reporting this issue:
```
h(n)
```

### The selected text was in the following section hierarchy:

1. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/csp/slides/fourqueens-ex.en.tex<br/>FetchURL: archive=MiKoMH/AI&filepath=csp/slides/fourqueens-ex.en.xhtml

**Comment by kohlhase** [comment]
I do not see what is missing, ...

**Comment by abchugh** [comment]
Can't fix. Unfortunately, not clear what the user finds missing.
