### ISSUE TITLE
ERROR in sTeX file

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#35]
A content ERROR was logged by a user at the following url:

https://courses.voll-ki.fau.de/browser/%3AsTeX%2Fdocument%3Farchive%3DMiKoMH%2FAI%26filepath%3Dcourse%2Fnotes%2Fnotes.xhtml?inDocPath=-qxa9pm.-z4t3oa

## The issue as described by the user:
```
Symbol for conjunction is wrong
```

## The text highlighted while reporting this issue:
```
TeX Macro:\lconjNotations:
          identifiernotationoperator notationin module(None)##1a∧##1b∧(here)bullet##1a∙##1b∙(here)amp##1a&##1b&(here)comma##1a,##1b,(here)
```

### The selected text was in the following section hierarchy:

1. GitLab: https://gl.mathhub.info//-/blob/main/source/<br/>FetchURL: /:sTeX/declaration?http://mathhub.info/smglom/logic/mod?conjunction?conjunction&language=en

**Comment by Jazzpirate** [comment]
`Symbol for conjunction is wrong` - ...no, it's not...?

**Comment by abchugh** [comment]
For posterity, the user was referring to this content:
https://stexmmt.mathhub.info/:sTeX/declaration?http://mathhub.info/smglom/logic/mod?conjunction?conjunction&language=en

**Comment by Jazzpirate** [comment]
yupp, that's also what I checked, and all the notations/symbol usages there look good to me?

**Comment by abchugh** [comment]
Yes. I think the user expected the programming OR symbol `||`. Shame that there is no easy way for them to see this discussion. I will work on a feature so that the user id (or some info like name) is optionally retained in the issue.

**Comment by kohlhase** [comment]
yes, that would really be good. Maybe they can given the option to give  their github account, ...
