### ISSUE TITLE
Sentence structure

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#41]
A content ERROR was logged by a user at the following url:

https://courses.voll-ki.fau.de/course-view/ai-1?deckId=MiKoMH%2FAI%7C%7Cprereq%2Fslides%2Fcomplexity-recap.en.xhtml&slideNum=5&viewMode=SLIDE_MODE&audioOnly=false

## The issue as described by the user:
```
If someone could proofread this whole paragraph, it would be helpful. In the third line "complexity class problem class" does not seem to fit as it is in the sentence. Also, there is no space between "class" and "problem". There is another similar issue in the paragraph.
```

## The text highlighted while reporting this issue:
```
But what is this notion of
NP-completness
        alluded to above? We observe that we can analyze the
complexity
        of
computational problems
        by the
complexity classcomplexity of the
algorithms
        that solve them. This gives us a notion of what to expect from solutions to a given
complexity classproblem class, and thus whether efficient (i.e.
polynomial time)
algorithms
        can exist at all.
```

### The selected text was in the following section hierarchy:

1. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/prereq/snip/np-trans.en.tex<br/>FetchURL: archive=MiKoMH/AI&filepath=prereq/snip/np-trans.en.xhtml

**Comment by kohlhase** [comment]
Thanks for the correction. I have fixed this in the sources. It will be a while until this reaches the production system though.
