### ISSUE TITLE
reinstate the average points feature for past quizzes

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX-React#433]
Here is a request from the AI-1 students just coming in: They would like us to reinstate the average points feature for past quizzes.

**Comment by abchugh** [comment]
This was removed to lower the load on sql server to avoid outages. Note that the dashboard will still not show each student's individual score. As a workaround, they can click on the quiz and see their score. Its not ideal but I will reenable it next week after I am confident that the average score change doesn't cause any performance issues.

**Comment by abchugh** [comment]
But the average quiz scores are now available again
