### ISSUE TITLE
quiz demo has regressed

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX-React#47]
it seems that there is nothing now at https://courses.voll-ki.fau.de/quiz

**Comment by kohlhase** [comment]
The same holds for the visualization. It only shows single nodes in very large.

**Comment by kohlhase** [comment]
at https://courses.voll-ki.fau.de/visualization

**Comment by abchugh** [comment]
The quiz demo deteriorating is expected. That implementation was a complete
hack. Slight updates in sTeX to html rendering will cause issues. I have
asked Dennis for annotations to build something proper.

**Comment by kohlhase** [comment]
OK, I am looking forward to seeing a less hacky version. Quizzes (and their integration into the guided tours and flash cards must be the next greater feature).

**Comment by abchugh** [comment]
Waiting for https://github.com/slatex/sTeX/issues/378 to get fixed and some sample content to be built.

**Comment by abchugh** [comment]
Quiz demo has been updated using sTeX3.3 annotations and is available on staging server at https://courses-staging.kwarc.info/quiz
Of course, this will not work on prod till it starts using sTeX3.3

**Comment by kohlhase** [comment]
excellent thanks. I will (at some point) start a tracker where I write down my suggestions
