### ISSUE TITLE
User reported ERROR 

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#62]
A content ERROR was logged by "a user" at the following url:

https://courses.voll-ki.fau.de/flash-cards/ai-1

## The issue as described by the user:
```
.
```

## The text highlighted while reporting this issue:
```
Definition 0.1.
          The
Wumpus world
          is a simple game where an
agent
          explores a cave with 16
cells
          that can contain
pits,
gold, and the
Wumpus
          with the goal of getting back out alive with the
gold.
```

### The selected text was in the following section hierarchy:

1. GitLab: https://gl.mathhub.info//-/blob/main/source/<br/>FetchURL: /:sTeX/fragment?http://mathhub.info/MiKoMH/AI/logic/slides?wumpus-world?Wumpus

**Comment by abchugh** [comment]
This refers to the `Wumpus` card in `Propositional Logic`

**Comment by abchugh** [comment]
![Screenshot](https://user-images.githubusercontent.com/5623836/216654091-8a21389c-c01a-4e85-934f-8ad66e6ed725.png)

**Comment by kohlhase** [comment]
That much I understood, but I cannot see what the "error" might be.

**Comment by kohlhase** [comment]
Ah, OK, I am assuming this will be fixed with the new sTeX3.3 content.
