### ISSUE TITLE
User reported ERROR game-play/slides/alpha-ex.en.xhtml

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#66]
A content ERROR was logged by "a user" at the following url:

https://courses.voll-ki.fau.de/browser/%3AsTeX%2Fdocument%3Farchive%3DMiKoMH%2FAI%26filepath%3Dcourse%2Fnotes%2Fnotes.xhtml?inDocPath=-9gxrd5.dwvm60.4bgu6x

## The issue as described by the user:
```
Unreadable labels with weird symbols
```

## The text highlighted while reporting this issue:
```
Max
                  −∞;α=−∞
                  
                    
                      
                    
                  
                  Max
                  3;α=3
                  
                    
                      
                    
                    
                  
                  Min
                  ∞;α=−∞
                  
                    
                      
                    
                    
                  
                  Min
```

### The selected text was in the following section hierarchy:

**_INNERMOST SECTION FIRST_**

1. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/game-play/slides/alpha-ex.en.tex<br/>FetchURL: /:sTeX/fulldocument?archive=MiKoMH/AI&filepath=game-play/slides/alpha-ex.en.xhtml

2. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/game-play/sec/alphabeta.en.tex<br/>FetchURL: /:sTeX/fulldocument?archive=MiKoMH/AI&filepath=game-play/sec/alphabeta.en.xhtml

3. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/game-play/sec/game-play.en.tex<br/>FetchURL: /:sTeX/fulldocument?archive=MiKoMH/AI&filepath=game-play/sec/game-play.en.xhtml

4. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/course/notes/notes.tex<br/>FetchURL: :sTeX/fulldocument?archive=MiKoMH/AI&filepath=course/notes/notes.xhtml

**Comment by kohlhase** [comment]
This is a consequence of the overlays functionality I am using in Beamer slides in LaTeX. This is not supported in our HTML workflow (and also not in the course notes), it only works in the PDF slides at the moment.

**Comment by kohlhase** [comment]
solved with slideshow
