### ISSUE TITLE
Chromium Font

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#70]
A content ERROR was logged by "a user" at the following url:

https://courses.voll-ki.fau.de/browser/%3AsTeX%2Fdocument%3Farchive%3DMiKoMH%2FAI%26filepath%3Dcourse%2Fnotes%2Fnotes.xhtml?inDocPath=-5bnm8o.-tni5cc

## The issue as described by the user:
```
In Chromium both of those "S"es look identical, but not in Firefox, where they are displayed correctly. This is just an example, it happens very often at many places.
(Firefox, though, hangs when I try to submit reports there (even if uBlockOrigin is turned off))
(Kubuntu 18.04)
```

## The text highlighted while reporting this issue:
```
S⊆S
```

### The selected text was in the following section hierarchy:

**_INNERMOST SECTION FIRST_**

1. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/planning/slides/conformant-search.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=planning/slides/conformant-search.en.xhtml

2. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/planning/sec/conformant-planning.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=planning/sec/conformant-planning.en.xhtml

3. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/planning/sec/acting.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=planning/sec/acting.en.xhtml

4. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/course/notes/notes.tex<br/>FetchURL: https://stexmmt.mathhub.info/:sTeX/fulldocument?archive=MiKoMH/AI&filepath=course/notes/notes.xhtml

**Comment by Jazzpirate** [comment]
*sigh* it seems MathML support in chromium does not recognize the `mathvariant`-attribute. It also seems to be faded out / to-be-deprecated in MathML-core in general in favor of unicode. This means rustex will have to convert all the font variants (bold, italic, script, blackboard) *and* combinations of those to their respective unicode manually. That's easily doable, but time consuming manual labour :-/

**Comment by kohlhase** [comment]
I believe that `mathvariant` and so on are all but "deprecated" by the MathML working group. And now some system (in this case chrome, but in the past it often was firefox) has added "incentive" to make it so, ...

**Comment by Jazzpirate** [comment]
already on it. Next rustex version will convert "font modifiers" in mathml to the corresponding unicode

**Comment by Jazzpirate** [comment]
Fixed. I'll rebuild on staging server. Also, I fixed the kerning problem with listings-text overlapping with the line numberings
