### ISSUE TITLE
Typo in Definition

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#71]
A content ERROR was logged by "Silas Kuder" at the following url:

https://courses.voll-ki.fau.de/browser/%3AsTeX%2Fdocument%3Farchive%3DMiKoMH%2FLBS%26filepath%3Dcourse%2Fnotes%2Fnotes.xhtml?inDocPath=-a9hqx2.g9ot2w.bm5v9r

## The issue as described by the user:
```
*ARE* traditionally written as
```

## The text highlighted while reporting this issue:
```
Inference rules
          as traditionally written as
```

### The selected text was in the following section hierarchy:

**_INNERMOST SECTION FIRST_**

1. GitLab: https://gl.mathhub.info/smglom/logic/-/blob/main/source/mod/inference-rule.en.tex<br/>FetchURL: /:sTeX/fulldocument?archive=smglom/logic&filepath=mod/inference-rule.en.xhtml

2. GitLab: https://gl.mathhub.info/MiKoMH/GenCS/-/blob/main/source/logic/slides/calculus-infrules.en.tex<br/>FetchURL: /:sTeX/fulldocument?archive=MiKoMH/GenCS&filepath=logic/slides/calculus-infrules.en.xhtml

3. GitLab: https://gl.mathhub.info/MiKoMH/LBS/-/blob/main/source/logic/sec/calculi.en.tex<br/>FetchURL: /:sTeX/fulldocument?archive=MiKoMH/LBS&filepath=logic/sec/calculi.en.xhtml

4. GitLab: https://gl.mathhub.info/MiKoMH/LBS/-/blob/main/source/logic/sec/formal-systems.en.tex<br/>FetchURL: /:sTeX/fulldocument?archive=MiKoMH/LBS&filepath=logic/sec/formal-systems.en.xhtml

5. GitLab: https://gl.mathhub.info/MiKoMH/LBS/-/blob/main/source/logic/sec/intro.en.tex<br/>FetchURL: /:sTeX/fulldocument?archive=MiKoMH/LBS&filepath=logic/sec/intro.en.xhtml

6. GitLab: https://gl.mathhub.info/MiKoMH/LBS/-/blob/main/source/course/notes/notes.tex<br/>FetchURL: :sTeX/fulldocument?archive=MiKoMH/LBS&filepath=course/notes/notes.xhtml

**Comment by kohlhase** [comment]
thanks for notifying, fixed on devel
