### ISSUE TITLE
Missing Comma?

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#72]
A content ERROR was logged by "Silas Kuder" at the following url:

https://courses.voll-ki.fau.de/browser/%3AsTeX%2Fdocument%3Farchive%3DMiKoMH%2FLBS%26filepath%3Dcourse%2Fnotes%2Fnotes.xhtml?inDocPath=-49loyw.-azln3m.dauiy9

## The issue as described by the user:
```
the double "in" seems wrong
```

## The text highlighted while reporting this issue:
```
What we are really interested in in
natural language semantics
```

### The selected text was in the following section hierarchy:

**_INNERMOST SECTION FIRST_**

1. GitLab: https://gl.mathhub.info/MiKoMH/ComSem/-/blob/main/source/nlsem/slides/what-overview.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/ComSem&filepath=nlsem/slides/what-overview.en.xhtml

2. GitLab: https://gl.mathhub.info/MiKoMH/ComSem/-/blob/main/source/nlsem/sec/nlmodel-logic.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/ComSem&filepath=nlsem/sec/nlmodel-logic.en.xhtml

3. GitLab: https://gl.mathhub.info/MiKoMH/LBS/-/blob/main/source/logic/sec/intro.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/LBS&filepath=logic/sec/intro.en.xhtml

4. GitLab: https://gl.mathhub.info/MiKoMH/LBS/-/blob/main/source/course/notes/notes.tex<br/>FetchURL: https://stexmmt.mathhub.info/:sTeX/fulldocument?archive=MiKoMH/LBS&filepath=course/notes/notes.xhtml

**Comment by kohlhase** [comment]
thanks for notifying, fixed on `devel`
