### ISSUE TITLE
Word doubling

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#73]
A content ERROR was logged by "Silas Kuder" at the following url:

https://courses.voll-ki.fau.de/browser/%3AsTeX%2Fdocument%3Farchive%3DMiKoMH%2FLBS%26filepath%3Dcourse%2Fnotes%2Fnotes.xhtml?inDocPath=7uzlwq.-l756wp

## The issue as described by the user:
```
functional programming appears twice
```

## The text highlighted while reporting this issue:
```
and
functional programmingfunctional
programming language
```

### The selected text was in the following section hierarchy:

**_INNERMOST SECTION FIRST_**

1. GitLab: https://gl.mathhub.info/MiKoMH/LBS/-/blob/main/source/gf/slides/gf-nutshell.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/LBS&filepath=gf/slides/gf-nutshell.en.xhtml

2. GitLab: https://gl.mathhub.info/MiKoMH/LBS/-/blob/main/source/gf/sec/frag1-gf.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/LBS&filepath=gf/sec/frag1-gf.en.xhtml

3. GitLab: https://gl.mathhub.info/MiKoMH/LBS/-/blob/main/source/nlfrags/sec/frag1-glif.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/LBS&filepath=nlfrags/sec/frag1-glif.en.xhtml

4. GitLab: https://gl.mathhub.info/MiKoMH/LBS/-/blob/main/source/course/notes/notes.tex<br/>FetchURL: https://stexmmt.mathhub.info/:sTeX/fulldocument?archive=MiKoMH/LBS&filepath=course/notes/notes.xhtml

**Comment by kohlhase** [comment]
thanks for notifying, fixed on `devel`
