### ISSUE TITLE
Metadata Format/Schema for Math Archives (Courses, Libraries, Papers, Talks,...)

### ISSUE THREAD

**Issue by Jazzpirate** [slatex/sTeX-React#82]
I think what we want to be able to generate from metadata are exactly these:
<img width="587" alt="thumbs" src="https://user-images.githubusercontent.com/12137632/235671910-35915c1c-420e-4061-9cae-8e5120d26ba8.png">

i.e. small informative link-like thumbnail thingys, grouped by... something. Currently by "current semester" and "other courses", but if we want to open up the system to other kinds of contents we need to think about this as well.

What information do we need? 
I would claim:
1. type of object, e.g.
   1. article-like (e.g. papers)
   2. library-like (e.g. smglom/algebra? Or rather all of smglom?)
   3. lecture-like (e.g. AI? AI1?)
   4. Is the sTeX Documentation an article-like thing?
2. where is the object - reference to a tex file / folder / ... - probably depends on the type of object. For courses, we would further distinguish between e.g. slides and notes - possibly even sections?
3. thumbnail image(?)
4. for courses: landing page *per semester*
5. for libraries: stubs, as in `descr` in the MANIFEST.MF? Do we also do this in sTeX or html or plain text?
6. for libraries: what does the entry thumbnail thingy link to? Something browser-like? Or all the contents directly, analogous to "all.pdf" or a guided tour (except for the guidance)?
7. for articles - probably title + authors + something abstract-like?
8. What about talks / slides? Is a talk a "thing" or the whole archive? Are the `slides`-directories libraries?

**Comment by Jazzpirate** [comment]
@abchugh I just realized that "Notizen" is a poor translation for "notes" *in that context*. "Skript" would probably be better, but I can't find the relevant file for the translations

**Comment by abchugh** [comment]
Take a look here and change all that need to be updated:
https://github.com/search?q=repo%3Aslatex%2FsTeX-React%20notizen&type=code

**Comment by kohlhase** [comment]
I really like the general setup and in particular keeping the information locally. For courses, i think we also need the following information: 
* which university/program the course is given in. 
* which semesters it is given.

**Comment by kohlhase** [comment]
I just made a course page for AI-1: `MiKoMH/AI/source/course/notes/coursepage1.en.tex`. 

I will make `coursepage1.de.tex` and `coursepage2.*.tex` to have the most general setup for practicing.

**Comment by Jazzpirate** [comment]
archive.json: A JSON array of objects with field "type":"course"|"library"|"article"|"book". Remaining fields are determined by the type

- course:
  - "title": e.g. "Artificial Intelligence I"
  - "institution": e.g. "FAU"
  - "semester": e.g. "SS23", "WS22/23"
  - "landing": landing page (current/last semester); file path relative to the source folder 
  - "notes": file path relative to the source folder
  - "slides": file path relative to the source folder
  - "past": Past semesters; a sequence of objects with fields "semester" and "landing" (as above)
  - "thumbnail": file path relative to the source folder

- library:
  - "title": e.g. "Basic Algebra"
  - "thumbnail": (see above)
  - "teaser": Plain text description for the thumbnail thingy
  - "landing"(?) as above; short introductory text before the individual modules
  - "dir": file path relative to the source folder, or "." if missing
I suggest that other than landing, a library's frontend page is just all the files in the directory in a sequence; analogous to guided tours

- article:
  - "title"
  - "authors" (for the thumbnail)
  - "thumbnail" (?)
  - "teaser" (?) (abstract might be too long for a thumbnail-like thingy
  - "file": file path relative to the source folder (i.e. the main .tex file)

- book:
  - "title"
  - "authors"
  - "thumbnail"
  - "teaser" (?)
  - "file"
  - "chapters" (?)

Importantly, that allows for having multiple objects of different types in the same repository

Not sure yet:
- How talks and individual slides might fit into the above are talks top-level objects?
- We might want a "regex" field to filter for specific files. For example, in "talks", we could have a library of slides and... other objects for the actual talks
- How to organize things all together - e.g. are all the smglom libraries just flat on the main page? Do we want them to be grouped under "smglom"? How about the courses - grouped by archive group (MiKoMH) or nstitution or semester?
- if we group things - do we need thumbnail/title/etc for the groups as well, including a landing page? If so, should they go into the meta-inf repositories?

**Comment by Jazzpirate** [comment]
>     * Yes, I think talks should definitely be top-level objects. I was a bit surprised they weren't in the original lineup. They could also include a field "link" or something to point to a recording (either local or with a URL).

The reason why I marked that with question marks and put it up for discussion is that we have *lots* of talks and they are *rarely* interesting. So grouping them together as subobjects in... "something else" seems more reasonable to me. But I don't have a good intuition for what that "something else" would be.

> 
>     * Generally, I feel like these lists of fields are not exhaustive. Probably no list we come up with will be. We probably want some general-purpose fields like "link" or "auxiliary file" or something like that. I'm picturing people uploading PDFs with required reading to course/seminar pages and such.

I think there's some confusion. The information in the json is intended for the frontend to actively generate entry points/thumbnails/services from. As such, the only information we need (or in fact *want*) to put in the json is that which the frontend can do something with. They will be exhaustive in the sense that additional information with no associated functionality is for all practical purposes useless. For example, links to auxiliarly files belong to wherever they are being linked from - e.g. the landing page. Putting them in the metadata only makes sense if the frontend is charged with doing something with that information ;)

**Comment by Jazzpirate** [comment]
> They could also include a field "link" or something to point to a recording (either local or with a URL).

This however is a good point. I would imagine that such a link would go in the "thumbnail-thingy" (I really need a better term for the... cards for the top-level objects that are on the home page of the portal), probably? Like we currently have for "notes", "slides" and "flashcards"?
I could imagine three ways to go about this:
- A fixed set of "entry links" (e.g. "notes", "slides", "flashcards", "video") would allow for having nice icons and mutlilinguality, as they currently do
- Arbitrary configurable links with configurable link titles in the json. The we can get rid of "notes" and "slides" as well and just have a "links" array or something
- something in between the two

**Comment by Jazzpirate** [comment]
In light of that I retract my earlier statement - I think I misunderstood what you meant :D
So: if by "exhaustive" you mean "final", then I agree. I'm sure we will come up with more functionality and corresponding metadata as we go along :) We should still think about what we want *initially*, and ideally fix a schema that we can easily *extend* in the future without needing to completely overhaul everything :)

**Comment by kohlhase** [comment]
I like where the discussion is going and I think a structured JSON file is the way to go. But I do my best thinking and discussing when we have concrete examples; and I think we can do that by now. 
Why don't we  pick three examples (course, publication, library) and make concrete JSON files so that we can get an overview? I suggest
* The AI notes (I have landing page texts for those in sTeX already) 
*  The paper https://gl.mathhub.info/Papers/22-TUG-sTeX (it is published already and thus better than the submitted CICM paper)
* the SMGloM library https://gl.mathhub.info/smglom/sets

**Comment by kohlhase** [comment]
> 5\. or libraries: stubs, as in `descr` in the MANIFEST.MF? Do we also do this in sTeX or html or plain text?

The `description` field (which traditionally points to a file `descr.html` with a HTML fragment) was a stop-gap for generating front-end of [MathHub.info](https://mathhub.info) . There was also a (text-only) `teaser` field in `MANIFEST.MF`  which was used in the [library list in MathHub](https://mathhub.info/library). The `descr.html` file was used in the [library landing page](https://mathhub.info/library/group/SGVsbG9Xb3JsZA==)

Thinking about this I realize two things: 
* are we re-imagining [MathHub](https://mathhub.info)  by generalizing beyond just the courses? 
* We need to have something that not only works for the sTeX stuff on https://gl.mathhub.info, but is "format-agnostic", so the format should probably be format-dependent (as long as HTML can be generated from it), i.e. sTeX for the sTeX-based archives and something else for the MMT-based ones. 
* What do we do with existing the MathHub.info front-end?

**Comment by Jazzpirate** [comment]
> * are we re-imagining [MathHub](https://mathhub.info)  by generalizing beyond just the courses?

Yes, I think that is exactly what we need :)

> * We need to have something that not only works for the sTeX stuff on https://gl.mathhub.info/, but is "format-agnostic", so the format should probably be format-dependent (as long as HTML can be generated from it)

So far, nothing insists on sTeX - only on "files relative to the source directory". By MMT-convention, "relative to source" is equivalent to e.g. "relative to the html directory" if files have been built, so that is compatible with arbitrary other source formats.

**Comment by Jazzpirate** [comment]
> I like where the discussion is going and I think a structured JSON file is the way to go. But I do my best thinking and discussing when we have concrete examples; and I think we can do that by now. Why don't we pick three examples (course, publication, library) and make concrete JSON files so that we can get an overview? I suggest
> 
>     * The AI notes (I have landing page texts for those in sTeX already)
> 
>     * The paper https://gl.mathhub.info/Papers/22-TUG-sTeX (it is published already and thus better than the submitted CICM paper)
> 
>     * the SMGloM library https://gl.mathhub.info/smglom/sets

Yes to all of this, with a slight addendum: Depending on how we want to treat libraries or *groups* of libraries, we might want to not *only* take smglom/sets, but also, say, smglom/algebra and smglom/analysis, and *smglom* as a group - depending on whether we *want* to group libraries. This is somewhat relevant with how cluttered or organized we want the main page to be.

The same applies to the talks/slides repositories, so maybe we also want to add e.g. talks/voll-ki.

I think generally we should think about: 1. what do we want the home page to look like (i.e. what should be there), 2. what should the thumbnail-cards there look like, 3. what should their link targets look like, and finally 4. what do we need to specify to achieve that dynamically

**Comment by Jazzpirate** [comment]
also: I would add the sTeX documentation, because it's again a separate "type of object" (maybe?)

**Comment by kohlhase** [comment]
> 5\. or libraries: stubs, as in `descr` in the MANIFEST.MF? Do we also do this in sTeX or html or plain text?

The `description` field (which traditionally points to a file `descr.html` with a HTML fragment) was a stop-gap for generating front-end of [MathHub.info](https://mathhub.info) . There was also a (text-only) `teaser` field in `MANIFEST.MF`  which was used in the [library list in MathHub](https://mathhub.info/library). The `descr.html` file was used in the [library landing page](https://mathhub.info/library/group/SGVsbG9Xb3JsZA==)

Thinking about this I realize two things: 
* are we re-imagining [MathHub](https://mathhub.info)  by generalizing beyond just the courses? 
* We need to have something that not only works for the sTeX stuff on https://gl.mathhub.info, but is "format-agnostic", so the format should probably be format-dependent (as long as HTML can be generated from it), i.e. sTeX for the sTeX-based archives and something else for the MMT-based ones. 
* What do we do with existing the MathHub.info front-end?

**Comment by kohlhase** [comment]
Another thing that I realized that we will need to deal with (and I am not sure that this is actually represented in the JSON structure well) is recurring courses. I see the `semester` and `past`. But I am not clear how this translates (or should translate) into the user interface. Also I guess we should probably have a `upcoming` in analogy to the `past` for the planned lectures (at least `https://kwarc.info/courses` has that and it seems useful. In general, the KWARC courses page could be a good model.

**Comment by kohlhase** [comment]
I have started playing with Dennis proposal above, here is what I came up with for `MiKoMH/AI`. See https://gl.mathhub.info/MiKoMH/AI/-/blob/main/META-INF/archive.json for the original.
```
[
    {"type": "course",
     "title": "Artificial Intelligence I",
     "landing": "course/notes/coursepage1"
     "acronym": "AI-1",
     "instructors": [{"name": "Michael Kohlhase"}],
     "institution": "FAU",
     "notes": "course/notes/notes1",
     "slides": "course/notes/slides1",
     "thumbnail": "course/PIC/ai-1.webp",
     "instances": [{"semester": "WS16/17"},
		   {"semester": "WS17/18"},
		   {"semester": "WS18/19"},
		   {"semester": "WS19/20"},
		   {"semester": "WS20/21"}, 
		   {"semester": "WS21/22"}, 
		   {"semester": "WS22/23"}, 
		   {"semester": "WS23/24"},
		   {"semester": "WS24/25"}] 
    },

    {"type": "course",
     "title": "Artificial Intelligence II",
     "summary": "course/notes/coursepage2"
     "acronym": "AI-2",
     "instructors": [{name: "Michael Kohlhase"}],
     "institution": "FAU",
     "notes": "course/notes/notes2",
     "slides": "course/notes/slides2",
     "thumbnail": "course/PIC/ai-2.webp",
     "instances": [{"semester": "SS17"},
		   {"semester": "SS18"},
		   {"semester": "SS19"},
		   {"semester": "SS20"},
		   {"semester": "SS21"}, 
		   {"semester": "SS22"}, 
		   {"semester": "SS23"}, 
		   {"semester": "SS24", "instructors": [{"name": "Dennis Müller"}] },
		   {"semester": "SS25"}] 
    }
]
```
I took most of the inspiration from [the KWARC.info course page](https://kwarc.info/courses/ai1/) which is generated from https://gl.kwarc.info/kwarc/kwarc.info/www/-/blob/master/courses/ai1.md (and the same for `ai2.md`)

Note that (as intended by Dennis), the `MiKoMH/AI` archive provides two courses: AI-1 and AI-2, so there are two objects in the archive. 

I made some changes to Dennis' proposal above. 
* I added an `acronym` field
* I did not add an `id` field, but I think we probably should.
* Following the KWARC.info course page, I opted for a different model for specifying what `semester` and `past` are trying to do: instead of specifying the current and past semester, we specify all the semesters where this course has been given or is planned, and trust the ALEA system to know what the "current semester" is and select the "current" instance. So I dropped the `semester` field and renamed `past` to `instances`. 
* I added an `instructors` field (currently a list of objects that just have a `name`; we may want to make that more semantic in the future). Note that the `instance` of `SS24` of `AI-2` has a different instructor (Dennis takes over there). So I understand the objects in the `instances` to overwrite the information on the higher level. That seems a good mechanism at first glance. 

Some ideas what may be missing (things we have in the KWARC.info course page) 
* A link to the web resources
* A link to the assignments (homeworks); they are currently handled via PDF files in https://kwarc.info/teaching/AI/assignments, that should probably move to an ALeA service at some point as well. 
* A link to the book(s) a course is based upon. 
* Localization: In the course page we have a german version of the landing page, we can currently not accomodate this in the setup; but I would hate to throw things away. 
* That being said, an indication of the language the course is given in.

**Comment by kohlhase** [comment]
Pertaining to the `id` discussion in my last comment and the idea that an archive can offer multiple top-level objects, I am wondering whether modeling the course notes as 
```
     "notes": "course/notes/notes1",
     "slides": "course/notes/slides1",
     "landing": "course/notes/coursepage1"
```
is not completely wrong (or at least missing out on some possibilities), maybe instead we should have the `MiKoMH/AI` archive specify additional objects
```
{"id": "ai1:notes",
 "type": "book",
  "title": "AI-1 Course notes",
  "source": "course/notes/notes1",
  ...}

{"id": "ai1:slides",
  "type": "presentation",
  "title": "AI-1 Slides",
  "source": "course/notes/slides1"
  ...}

{"id": "ai1:landing",
  "type": "web fragment",
  "source": "course/notes/coursepage1"
  ...}
```
Then we could replace 
```
     "notes": "course/notes/notes1",
     "slides": "course/notes/slides1",
     "landing": "course/notes/coursepage1"
```
with document references 
```
     "notes": "ai1:notes",
     "slides": "ai1:slides",
     "landing": "ai1:landing"
```
Of course, in the course landing page we might also inline the object (or not, I have no good intuition here). 

I would like to have feedback on this idea.

**Comment by Jazzpirate** [comment]
Looks good to me :)

> Some ideas what may be missing (things we have in the KWARC.info course page)

They can probably largely be in the landing page, no? Putting them explicitly in the metadata only makes sense if the frontend is supposed to handle them in some special way. I don't think that would be the case for e.g. books or the language the course is in, but might be the case for *some* online resources or exercises.

> Localization: In the course page we have a german version of the landing page, we can currently not accomodate this in the setup

We (implicitly) do: If we assume that landing pages also have a language identifier in the filename (e.g. `.en.tex`, `de.tex`), frontend or backend can pick up on that and use the language set by a user by default (if existent).

> ertaining to the id discussion in my last comment and the idea that an archive can offer multiple top-level objects, I am wondering whether modeling the course notes as

...I'm not sure I understand this - does this add any functionality? Because this largely looks to me like it just introduces abbreviations for objects in the schema, which smells a bit like overengineering to me

**Comment by kohlhase** [comment]
> ...I'm not sure I understand this - does this add any functionality? Because this largely looks to me like it just introduces abbreviations for objects in the schema, which smells a bit like overengineering to me

I am not sure either, having the documents as separate objects provided by the archive might allow them to show up elsewhere. E.g. the course notes in MathHub as "sTeX books". Not just as a (local) link in the course page.

**Comment by kohlhase** [comment]
I am really happy about having the course pages as sTeX, then I can re-use things like the overview of topics and do not have to maintain them twice. Also they can be semantically annotated.

**Comment by kohlhase** [comment]
I have also added the IWGS infrastructure.

**Comment by kohlhase** [comment]
@abchugh @Jazzpirate 
OK, also added the infrastructure for LBS and KRMT, so we have enough material to start the development of the "generated course page" under https://courses.voll-ki.fau.de

**Comment by kohlhase** [comment]
I also specified the "book" for the ALeA Manual in https://gl.mathhub.info/voll-ki/ALeA/META-INF/archive.json. 
So we can also experiment with this.

**Comment by kohlhase** [comment]
@Jazzpirate 
Now I want to move on to the libraries (i.e. smglom). 
> library:
>     * "title": e.g. "Basic Algebra"
>     * "thumbnail": (see above)
>     * "teaser": Plain text description for the thumbnail thingy
>     * "landing"(?) as above; short introductory text before the individual modules
`title`, `teaser`, and `landing` are (morally) already in `MANIFEST.MF`, do you suggest we drop them from there? 
For libraries, there is also a problem where to put the `landing` page. Currently these are `html` fragments called `desc.html` in `META.INF`. But a crucial invariant (which I subscribe to completely) seems to be that all paths are relative to `source`. So, where to put `landing.en.tex`? We could 
* introduce a subdir `source/lib` and put it there. 
* directly put it into `source`, 
I am not sure.

**Comment by Jazzpirate** [comment]
> title, teaser, and landing are (morally) already in MANIFEST.MF, do you suggest we drop them from there?

I would suggest so - those were meant for mathhub-

> For libraries, there is also a problem where to put the landing page

It's not entirely clear to me that libraries *need* a landing page - mostly because it's not clear to me yet what the interface in the frontend for browing a library should be in the first place...

**Comment by kohlhase** [comment]
> It's not entirely clear to me that libraries _need_ a landing page - mostly because it's not clear to me yet what the interface in the frontend for browing a library should be in the first place...

I agree here, I struggled to come up with the `desc.html` in the past, and they are not helpful. So I think I would leave that out. Or at least make that (very) optional.

**Comment by Jazzpirate** [comment]
We should probably soon talk about what exactly the frontend should do with the information, i.e.: What should the "index" page look like and 2. What should the individual "entries" in that index look like and 3. What should the "link targets" of those "entries" look like.

**Comment by kohlhase** [comment]
Indeed, and I think we only have a clear picture for the courses page in ALEA. The others are probably more important for either MathHub or the build system. Here I am not quite sure what the mechanism should be. 
I have the vague idea that the `archive.json` files specify what the respective archive provides and that that can be used to see what the build system should download to provide a particular service.

**Comment by Jazzpirate** [comment]
I don't understand how the build system comes into play here at all...? The metadata, in my mind, specifies basically indices for some portal that allows browsing/accessing the content of archives in an organized manner. What that organization is exactly is the open question. The build system is an entirely separate beast that, on demand, compiles tex to html/omdoc, but it does not need to know anything about what the tex files represent.

**Comment by kohlhase** [comment]
I guess that I was still obsessing over the fact that I have no real model of how the ALeA system gets to find all the formulations for a given domain model element, and was thinking about how the archive.json could help.

**Comment by abchugh** [comment]
I believe that this is done. For enhancements, please create a new issue
