### ISSUE TITLE
Black lines in text

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#93]
A content ERROR was logged by "a user" at the following url:

https://courses.voll-ki.fau.de/course-view/ai-2?sectionId=1092f851&slideNum=2&viewMode=SLIDE_MODE&audioOnly=false

## The issue as described by the user:
```
Bottom half of the text is overlayed with black lines
```

## The text highlighted while reporting this issue:
```
n
```

**Comment by Jazzpirate** [comment]
correction: This is another case of plain HTML occurring in MathML which it shouldn't - this has already been fixed in RusTeX and will just require another run of the build server. Again things work fine in Firefox, but apparently React and Chrome trip over the "broken" MathML
