### ISSUE TITLE
Black lines in text

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#94]
A content ERROR was logged by "a user" at the following url:

https://courses.voll-ki.fau.de/course-view/ai-2?sectionId=1092f851&slideNum=5&viewMode=SLIDE_MODE&audioOnly=false

## The issue as described by the user:
```
Black line in text.
```

## The text highlighted while reporting this issue:
```
comments
```

**Comment by Jazzpirate** [comment]
Seems to be related to the frontend; the same slide likes perfectly fine in the mmt-viewer: https://stexmmt.mathhub.info/:sTeX/browser/fulldocument?archive=MiKoMH/AI&filepath=probabilistic-reasoning/slides/HMM.en.xhtml

**Comment by Jazzpirate** [comment]
Same here: It's actually RusTeX's fault, will be fixed with the next run of the build server
