### ISSUE TITLE
Black bars

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#96]
A content ERROR was logged by "a user" at the following url:

https://courses.voll-ki.fau.de/course-view/ai-2?sectionId=57bc9744&slideNum=2&viewMode=SLIDE_MODE&audioOnly=false

## The issue as described by the user:
```
A black bar hides the formulas
```

## The text highlighted while reporting this issue:
```
𝐏(𝐗𝑡+1|𝐞1:𝑡)
```

### The selected text was in the following section hierarchy:

1. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/probabilistic-reasoning/slides/Markov-filtering.en.tex<br/>FetchURL: https://stexmmt.mathhub.info/archive=MiKoMH/AI&filepath=probabilistic-reasoning/slides/Markov-filtering.en.xhtml

**Comment by kohlhase** [comment]
I cannot see any black bars, in firefox all looks fine.

**Comment by Jazzpirate** [comment]
this is probably the same one that we already had a couple of times (HTML-nodes in MathML, which firefox can deal with but chrome and react can't). This is already fixed and will disappear with the next run of the build server
